# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins: [jekyll-paginate]

# Permalinks
permalink:         /:year/:month/:day/:title:output_ext

# Setup
title:            Jen Sparks
tagline:          'A personal blog'
description:      'Exploring technology, crafts, and the universe.'
url:              http://jenrsparks.github.io
baseurl:          /

author:
  name:           'Jen Sparks'
  url:            https://twitter.com/chaosmuse_

paginate: 5
paginate_path: "page:num"

github:
  repo:           https://github.com/jenrsparks/jenrsparks.github.io

jekyll_get:
  - data: spells_phb
    json: 'https://raw.githubusercontent.com/TheGiddyLimit/TheGiddyLimit.github.io/master/data/spells/spells-phb.json'
    cache: true