# Dependencies
markdown:         redcarpet
highlighter:      pygments

plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Sparks
tagline:          'A personal blog'
description:      'Exploring technology, crafts, and the universe.'
url:              http://jenrsparks.github.io
baseurl:          /

author:
  name:           'Jen Sparks'
  url:            https://twitter.com/chaosmuse_

paginate: 5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jenrsparks
